* =org-roam-desktop= - An Unofficial Extension
This is a dead simple desktop facility for [[https://github.com/org-roam/org-roam][org-roam]]. It provides a
mechanism to collect and place nodes into a /desktop/-buffer. It is
based on [[https://github.com/localauthor/zk/blob/main/zk-index.el][zk's desktop]] and was modified to work with org-roam.

Please note that this is totally WIP and developed for my personal
use. Both the functionality and the interface will change. If you do
not want to tinker with it, keep off your hands.

* Overview and usage
** The Concept
=org-roam-desktop= let's you conveniently add nodes as headlines
followed by a =#+transclude=-link into an =*Org-Roam-Desktop*-...= of
your choice. This is just a buffer stored in a designated directory.
Its contents will look like this: 

#+begin_src 
,* [[id:7aaa1b8e-c776-44ec-8d65-150dea59cd1c][Some node]]
,#+transclude: [[id:7aaa1b8e-c776-44ec-8d65-150dea59cd1c][Some node]]

,* [[id:7d2fe829-ea12-4589-9d78-0b0c5009f593][Some other node]]
,#+transclude: [[id:7d2fe829-ea12-4589-9d78-0b0c5009f593][Some other node]]
#+end_src
(Commata included for escaping in org.)

** Sample workflow
In order to pull out some /zettels/ and put them on your desktop, use
the following commands:

1) Open a =*Org-Roam-Desktop--...= via =M-x org-roam-desktop=
2) Add a node to a new or existing
   =*Org-Roam-Desktop--= desktop of your choosing by running =M-x
   org-roam-desktop-node-add=. This let's you search and an
   =org-roam-node= which will be added to the desktop.
3) Eventually, you want to add the current node at point to a desktop.
   To do so, you can either call the previously mentioned function with
   prefix argument (=C-u C-c n a= if you are using the keybinding set
   below) or by running =M-x org-roam-desktop-node-at-point-add=
4) Afterwards, open the desktop via =M-x org-roam-desktop-select= (or just by
   using =M-x switch-to-buffer=) and edit it the buffer
 

* Preliminary Installation Steps

#+begin_src elisp
(use-package org-roam-desktop
   :straight (:host github :repo "jgru/org-roam-desktop")
   :init
   (require 'org-roam-desktop)
   :custom
   (org-roam-desktop-basename "*OR-Desk--")
   :config
   (setq org-roam-desktop-directory "/path/to/roam/desktops")
   :bind
   ("C-c n d" . org-roam-desktop)
   ("C-c n a" . org-roam-desktop-node-add))
#+end_src

* Dependencies
** Hard dependencies
=org-roam-desktop= is built on top of [[https://github.com/org-roam/org-roam][org-roam]] and relies on its
functionality.

** Soft dependencies
=org-roam-desktop= makes use of transcluding =org-roam-nodes=, it is
therefore advised to install [[https://github.com/nobiot/org-transclusion][org-transclusion]] as well.

* Credits
- [[https://github.com/localauthor/][localauthor]]'s =zk= for providing the implementation
- [[https://github.com/Vidianos-Giannitsis/zetteldesk.el][zetteldesk]] for fueling the idea
